version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0.9
    container_name: "gws-mongo"
    ports:
      - "27017:27017"

  consul:
    image: bitnami/consul
    container_name: "gws-consul"
    ports:
      - "8500:8500"
    command: "consul agent -dev -ui -client=0.0.0.0"

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: "gws-elasticsearch"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "gws-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "s@cr3t"
    ports:
      - "5672:5672"
      - "15672:15672"

  service-backend:
    build: ./service-backend
    ports:
      - "1001:1001"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: ./gateway
    ports:
      - "1000:1000"
    depends_on:
      - service-backend
      - rabbitmq
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

networks:
  default:
    name: gws-net
    driver: bridge

