server:
  port: 1000
  error:
    include-message: always
    include-binding-errors: always

oauth:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    scope: "openid profile email"

spring:
  application:
    name: gateway
  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
    gateway:
      routes:
        - id: gateway-oauth-route
          uri: lb://gateway
          predicates:
            - Path=/oauth/**
        - id: service-backend-route
          uri: http://localhost:1001/api/**
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/movie/(?<remaining>.*), /api/movie/${remaining}
            - RewritePath=/api/director/(?<remaining>.*), /api/director/${remaining}
        - id: service-frontend-route
          uri: http://localhost:3050/**
          predicates:
            - Path=/**
  r2dbc:
    url: "r2dbc:h2:mem:///gwsdb"
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

frontend:
  uri: "https://homework.d3quyrp7d48xeh.amplifyapp.com/"